cache:
  directories:
  - node_modules
sudo: false
language: node_js
node_js:
- '6'
before_install:
- npm install
script:
- npm run build-css
- npm test
- npm run build
notifications:
  slack:
    rooms:
      - secure: hLmNwol2KZ9D/2tvpVH6cpa0Ri07XthTc+92gyAIUnHKi8bOlLSuwUV28JumHxwMqcOeas5K1lq16nLt6K8eZzcwHVuUZRTPIwKJm96bnwS/z3TeTun2egnWxfnXotj+Bjrxjid9UtmZ9EnGUd1MfavVOn4q3O7u2kQHmBKbTSMOimmrjWcVjA1XBNNrj4Ec8I/9NZFmLmCzkzA2oyjEMfZ/RLvFSJz6JAdpomjMScIJ0W3abanZwXl6pN7ertfv6YSoPvmBKzjr28pdepDKHfRrQyN66OE+mLhVA2xFXrTAIVdeghN6F7U1XBMMRqvmgb2V8i449FVQc9e9Sjem7fYyOvZgg392Nef6xZ02zS/pNGZhXQbpnFrJ6HAl5ueFJGYaTAz0WGX+RQzzuTF78QIdg1Ye0sOXNpZeF+mnclQJvMVawq34F7NAWK0u+DGxLyhtGEx87wS/wVScseMD7dmBYHkBHGkznGJl+s+Uwsg0s+uK6beL9QgW3xifWbOnUzCif8BiPEU3xBUKpTdBFstSS96Ju1t+bltR6VGn/7OpQpoio1vwFmCdYxxlKrLGLP6A0Ybi7rkbVkXnSAjY6vW6/MJoE4W16otZiT65CB0qUH1TEhnD2+XhNkTnHbddRfzdqzd8T2DZNqk5V3IrtxnHjHtMbuLvvcdOYHKSAUc=